/*Question 1*/
/*SELECT * FROM JOBS where MIN_SALARY > 10000;*/
      
/*Question 2*/
/*SELECT FIRST_NAME, HIRE_DATE 
FROM EMPLOYEES 
where HIRE_DATE BETWEEN '2002-01-01' and '2005-12-31';*/

/*Question 3*/
/*SELECT EMPLOYEES.FIRST_NAME, EMPLOYEES.HIRE_DATE, JOBS.JOB_TITLE
FROM EMPLOYEES 
INNER JOIN JOBS 
ON EMPLOYEES.JOB_ID = JOBS.JOB_ID
where EMPLOYEES.JOB_ID = 'IT_PROG' or EMPLOYEES.JOB_ID = 'SA_MAN';*/

/*Question 4*/
/*SELECT FIRST_NAME, LAST_NAME, HIRE_DATE 
FROM EMPLOYEES
where HIRE_DATE > '2008-01-01';*/

/*Question 5*/
/*SELECT *
FROM EMPLOYEES 
where EMPLOYEE_ID = 150 or EMPLOYEE_ID = 160;*/

/*Question 6*/
/*SELECT FIRST_NAME, SALARY, COMMISSION_PCT, HIRE_DATE
FROM EMPLOYEES
where SALARY < 10000;*/

/*Question 7*/
/*SELECT JOB_TITLE,MAX_SALARY, MIN_SALARY, (MAX_SALARY - MIN_SALARY) as difference
FROM JOBS
where MAX_SALARY BETWEEN 10000 and 20000;*/

/*Question 9*/
/*SELECT * FROM JOBS
ORDER BY JOB_TITLE;*/

/*Question 10*/
/*SELECT FIRST_NAME, LAST_NAME 
FROM EMPLOYEES 
where FIRST_NAME like 'S%' and LAST_NAME like 'S%';*/

/*Question 10*/
/*SELECT * FROM EMPLOYEES where FIRST_NAME8*/

/*Question 11
select First_name
from employees 
where extract(month from hire_date) ='05'*/

/*Question 12
SELECT *
FROM employees
WHERE commission_pct is null
and salary between 5000 and 10000
and department_id=30;*/

/*Question 13
SELECT FIRST_NAME, HIRE_DATE, LAST_DAY(HIRE_DATE)+1 
FROM EMPLOYEES;*/

/*Question 14
SELECT EMPLOYEES.FIRST_NAME,JOBS.JOB_TITLE
FROM EMPLOYEES 
      INNER JOIN JOBS
        ON JOBS.JOB_ID = EMPLOYEES.JOB_ID;
        
/* Question 15
select First_name
from employees 
where extract(year from hire_date) ='2001'*/

/*Question 16
SELECT INITCAP(LOWER(FIRST_NAME)), INITCAP(LOWER(LAST_NAME))
FROM EMPLOYEES; */

/*Question 17 - Fonte: http://www.devmedia.com.br/expressoes-regulares-em-banco-de-dados-oracle/12504
SELECT JOB_TITLE, REGEXP_REPLACE(JOB_TITLE, '^(\w+)(.*?)(\w*$)', '\1')
from JOBS; */

/* QuestioN 18 --Fonte do INSTR http://www.willianparige.com.br/2012/10/usando-o-instr-no-oracle.html
SELECT LENGTH(FIRST_NAME),FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE INSTR(LAST_NAME,'b')>3 */

/*Question 19 --It was strange that the ...ARE SAME IRRESPECTIVE OF THE CASE
SELECT UPPER(FIRST_NAME), LOWER(EMAIL)
FROM EMPLOYEES
WHERE UPPER(FIRST_NAME)<>EMAIL; */

/*Question 20 -- Didn't return result for 2017
SELECT FIRST_NAME, LAST_NAME
FROM EMPLOYEES 
WHERE EXTRACT(YEAR FROM hire_date) = EXTRACT (YEAR FROM CURRENT_DATE);  
*/

/*Question 21
SELECT TRUNC(SYSDATE)- TO_DATE('20110101','yyyymmdd') -- TRUNC was used to round the SYSDATE, due to time.
FROM DUAL ;
*/

/* Question 22
Select MONTH_HIRE, COUNT(*)AS QUANT_EMPLOYEE
FROM(
        SELECT EMPLOYEE_ID,  EXTRACT(MONTH FROM hire_date)AS MONTH_HIRE
        FROM EMPLOYEES
        WHERE EXTRACT(YEAR FROM hire_date)=2006--EXTRACT (YEAR FROM CURRENT_DATE)
    )T
GROUP BY MONTH_HIRE
ORDER BY 1;
*/

/*Question 23
SELECT MANAGER_ID, COUNT(EMPLOYEE_ID) QUANT_EMPLOYEES
FROM EMPLOYEES
GROUP BY MANAGER_ID
*/

/*Question 24
SELECT EMPLOYEE_ID, END_DATE
FROM JOB_HISTORY;
*/

/*Question 25
SELECT COUNT(*)
FROM(
    SELECT EMPLOYEE_ID, EXTRACT (DAY FROM HIRE_DATE)AS DAY_HIRE, EXTRACT (MONTH FROM HIRE_DATE)AS MONTH_HIRE
    FROM EMPLOYEES 
    where EXTRACT (DAY FROM HIRE_DATE)>15
     )t;
*/

/*Question 26
SELECT COUNTRY_ID,COUNT(*)
FROM LOCATIONS
GROUP BY COUNTRY_ID;
*/

/*Question 27
SELECT DEPARTMENT_ID, AVG(SALARY)
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL
GROUP BY DEPARTMENT_ID;
*/

/*Question 28
SELECT JOB_ID, COUNT(*), SUM(SALARY), (MAX(SALARY)-MIN(SALARY))
FROM EMPLOYEES
GROUP BY JOB_ID;
*/

/*Questoin 29
SELECT JOB_ID
FROM (
        SELECT JOB_ID, AVG(SALARY) AVG_SALARY
        FROM EMPLOYEES
        GROUP BY JOB_ID
    )T
WHERE AVG_SALARY> 10000;
*/

/*Question 30
SELECT YEAR_HIRE,COUNT(*)
FROM(
    SELECT EMPLOYEE_ID, EXTRACT(YEAR FROM HIRE_DATE) AS YEAR_HIRE
    FROM EMPLOYEES
    )
GROUP BY YEAR_HIRE
HAVING COUNT(*) >10;
*/

/*Question 31
SELECT DEPARTMENT_ID
FROM(
    SELECT DEPARTMENT_ID,COUNT(*)QUANT_EMP_COMMI
    FROM EMPLOYEES
    WHERE COMMISSION_PCT IS NOT NULL
    GROUP BY DEPARTMENT_ID
    )T
WHERE QUANT_EMP_COMMI >5;
*/

/*Question 32
SELECT EMPLOYEE_ID,COUNT(*)QUANT_JOB
FROM JOB_HISTORY
WHERE END_DATE IS NOT NULL
GROUP BY EMPLOYEE_ID
HAVING COUNT(*) >1;
*/

/*Question 33 
SELECT JOB_ID,COUNT(*)QUANT_EMPLOYEE
FROM JOB_HISTORY
WHERE (END_DATE- START_DATE)>100
GROUP BY JOB_ID
HAVING COUNT(*) >3
ORDER BY 1
*/

/*Question 34
SELECT DEPARTMENT_ID, EXTRACT(YEAR FROM HIRE_DATE), COUNT(*)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID,EXTRACT(YEAR FROM HIRE_DATE) 
ORDER BY 1;
*/

/*Question 35
SELECT DEPARTMENTS.DEPARTMENT_NAME,EMPLOYEES.MANAGER_ID, COUNT(*)AS QUANT_EMPLOYEE
FROM EMPLOYEES
    INNER JOIN DEPARTMENTS
        ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
GROUP BY DEPARTMENTS.DEPARTMENT_NAME,EMPLOYEES.MANAGER_ID
HAVING COUNT (*) >5
ORDER BY 1;
*/